[Interface]
PrivateKey = cJ0mJ3tlUKr42aizKpLdVI8CYYqobS1tS+2zSp+p9W0=
Address = 10.80.3.20/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = nW69Fe8ZrlMv8sKuOhfUMYl7WLFZ8k46qSw8obAPiFY=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
