[Interface]
PrivateKey = GOwhol5aoEB3oaTwcGvbBBm7h/c/xfjNGJ8GgUBSfkY=
Address = 10.80.3.22/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = x7GxqpmuKb9lJwJlsEdZJmYdvpGlaVu3yx7J2d34/gw=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
