[Interface]
PrivateKey = EF68Dbw3Z5jTta9nFr+XTNykvzZmKKr4zcPVTARzVns=
Address = 10.80.3.10/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = KboTu5KKUJeaAFUkOHaPCf6qe+csHQMJ6tS4G8lSj14=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
