[Interface]
PrivateKey = 0Hl/iFGuF6A32b7MGsereNhBesg7QOpFA3qemLbFu00=
Address = 10.80.3.2/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = pR1eKfjYWI5OPUn8rzZtNLMIgITSiU/dTpNrHOsntws=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
