[Interface]
PrivateKey = 6M8IsiGSvxPTe5rY8QArVvsC/7I3TayHDrQ6LR+QR0k=
Address = 10.80.3.29/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = XIbnAxuCS0Hvt1QSXnA/QcN3DkoLC1o3WfFi9fuH63Y=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
