[Interface]
PrivateKey = AISVe7w5qzxX1aUvjLq0RG+8vqMsukXDIb7ESSJ7WGM=
Address = 10.80.3.15/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = BzlTEEzThG4po/Jm6/eXT7n3csRz0Smbne7+wonN8sw=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
