[Interface]
PrivateKey = 6OfjSOEOlCQm0Ubybc2POmBOvIwR5KfC1s/5X2j1+GY=
Address = 10.80.3.9/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = oYX1zevBLim9EX+rQntjCTXj6yAmLtl8Z2Rkmt0+9NY=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
