[Interface]
PrivateKey = OPJsmui2h5t5IevFw2GJol7h8lrP1c4jVYEH/0igaHo=
Address = 10.80.3.21/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = zLEn/eqLEm3hJe6bBiE5qHFK9qVXuG/RiPlpOD0KnWA=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
