[Interface]
PrivateKey = QHIF4EvTgW0LO4mK3Os8kVw9yQWlbrWBq+BmN+8fpXo=
Address = 10.80.3.5/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = 4luSluV0k0xBAu2/kC1dScnXHh46UwLvoYkTtAu0mgg=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
