[Interface]
PrivateKey = MAYzZxrfQ0pOtAqC7YhLcChkSLV58sabaUaJy4pfImw=
Address = 10.80.3.6/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = nJ+Y0yv4sFEupJzBS4JfqDxM2kAA/KhvT6RrAjaYH2Y=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
