[Interface]
PrivateKey = YGgrEx3/O2/ZrG0hD6dqvLFV4PnO5jfUmavWVzp70WQ=
Address = 10.80.3.17/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = ItGBodAnZnqKpTUUZXQjH1G4mDnQwvq1coPnMZ5dXtc=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
