[Interface]
PrivateKey = +K0tm9SPxKc/en6O67JAQYZYR7KT+YZS3MbGExP4JmI=
Address = 10.80.3.27/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = usJ+LUpzQjr+E2iNlFgmr15z+UaW3oLeMYGXyNGuy9M=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
