[Interface]
PrivateKey = cP/F/9Ga2+KzP+OuhUfAc3Hl8u8IyU2iQkCoz2APcXI=
Address = 10.80.3.26/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = W/+GyN60samTxA7DGhJ7Bpd6/r+syQ+ThR9QUH+OHPY=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
