[Interface]
PrivateKey = uKyDDFjsraN1D+JeKcYpiu2BxuuCUXpnXeAwQ+5WM10=
Address = 10.80.3.8/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = ZrYzOUn+8S4c0we718lt7LXC5AIrso6Fk0/VLxx5wcE=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
