[Interface]
PrivateKey = EFAPjMzIifT/5ymtwb3Wn+hViJJzNREpPOh3rOlpBmo=
Address = 10.80.3.7/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = Aol90I6t+MVe0+9SAWbP3DIKBCni6ZGNKAIe1JuLNOE=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
