[Interface]
PrivateKey = 8J/DNcv5ONTa3ZNPctKURSWN4cL611xqqOdaxoZp5Uc=
Address = 10.80.3.1/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = yJvyHBlFQ4jsROc3tV9qPFnx9d0BIptUJTIIRli6Fqo=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
