[Interface]
PrivateKey = SBTR/8vM+YlEXHe0eMo6p4exmGlmSngJ1NnJFyRH8ks=
Address = 10.80.3.25/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = yb88gG5qHXlPQUfus/gWA6uPXSGYZ/lHJYUFPb/WKlY=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
