[Interface]
PrivateKey = OFOUJZVyr8+Z3VUINQCO8LJSkWvhI/wuOPbbnz8ZfE8=
Address = 10.80.2.17/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = EKzry0QiELTX/WbY2/CvwqWo/jOHPBwBHolag9UP7yQ=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
