[Interface]
PrivateKey = KLMU4iZOdybFJhdmy1K5gO0ii4S2RtvEsswQZKxIZ2M=
Address = 10.80.2.24/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = 6zfVSTA4uwNZb2xtFB8yOOTV612cAdkg04WcUxR95a0=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
