[Interface]
PrivateKey = SF9gn9+u20qfCqRvMszzJAtTNn5Kmmt3ye5nAZ1AfFI=
Address = 10.80.2.23/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = +TyBI+bBlCxY6DN9ace84L3zBFy3VWCtAratwsGOkNs=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
