[Interface]
PrivateKey = iIijy56IQI3Hs+rnZHGu2p7QgaHgHWvlinvF/A+Ohk4=
Address = 10.80.2.20/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = n+6O4E+w04i73p8DhSuNQO5jj5hE3Uut3iojLSa2QAQ=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
