[Interface]
PrivateKey = SD9qJqCnda0fc9e5//ga9tFps9KIjnXCXmnsY1CJemQ=
Address = 10.80.2.6/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = mqfXF0+mGDOBymhAxt+P5LUMSVNs8MGeFgRjTsZXctA=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
