[Interface]
PrivateKey = YFKzGiw5szf5V0UGbLZKGP3GPJ2N9utW/8VRnk6xgkw=
Address = 10.80.2.15/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = W+Xje7ZVf391muBQQRU4pm6g3RRVhRNMyBfAOMP6Njw=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
