[Interface]
PrivateKey = GCEOgsAB1/sHqJ7+zN6gplLHdQQPsc/7kYyWHnyfJlI=
Address = 10.80.2.3/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = AIhhRO4sadhiJn7JU5upufoXaAXSAI3aHu6zYdE6KuA=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
