[Interface]
PrivateKey = iHSMhsEO+jhUmnjA+kTkPX7J5iUJ+kAgXu0wPXB5c3E=
Address = 10.80.2.8/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = 6ZOnyYq2c/xBhTHKlqE8zvK2BJJouF6+lWSgX3Y7fQI=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
