[Interface]
PrivateKey = MOAvdJ6kgUiah1bOCcpNvU81GbXi/3xwLQfk28ESClw=
Address = 10.80.2.27/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = U+Pkbpm2mW2rpyB+gFfEvI2iApOd24LgDULWWy67Olw=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
