[Interface]
PrivateKey = gALZL8bJAvhDyfPlIS6buyRRkj7nZUQOPwl28Vujz3Q=
Address = 10.80.2.9/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = Efn+EDrtdDnBXvJBCt5+LT1wFK2PB2p52+McP3xa38w=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
