[Interface]
PrivateKey = AFVIcMHPB99deveE2Sz9cXg3NjEESya0VlKCaXQWb3A=
Address = 10.80.2.11/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = gWnX9XLS5RXAD6M/mswVCYW1tcZWr+wUqbzfuSwEERY=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
