[Interface]
PrivateKey = CIN+FuWS+W7Iu1bbjz+7RoufQYOLnUy/++aOReK1T2Q=
Address = 10.80.2.29/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = JcxGJKyn2OuigJS7JD+hU3Iinv8dr6FcQs/Caqv6Yu0=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
