[Interface]
PrivateKey = CEvAKXwmLhkDXfeD1f1r/8Pdv6gsIsm7yb3eKV3WwEw=
Address = 10.80.2.26/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = UI5gnETqcxOjhoM6SY5R5C5EsokYn/KkmXnkfl7xosw=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
