package main

import (
	"context"
	"encoding/json"
	"net"
	"net/http"
	"strconv"
	"strings"
	"time"

	"game/db"
	"game/log"

	"github.com/gorilla/mux"
)

// ----------------------------------------------------------------------------
// authorization
// ----------------------------------------------------------------------------

/*
	The control room is not protected by a password: it is protected by the
	network it is reached from. The admin WireGuard profiles generated by
	confgen.py live in 10.80.253.0/24, and WireGuard only accepts a packet whose
	source address matches the AllowedIPs of the peer that signed it. Holding an
	admin profile is therefore what proves you are an organizer, and there is no
	extra secret to leak, rotate or type into a laptop at a competition desk.

	The loopback address is allowed too, so that the organizers can still drive
	the API with `docker exec` on the control node if they lose VPN access.
*/

// adminVPNNetwork is the subnet confgen.py hands to the admin WireGuard
// profiles. It is the only way in, on purpose: there is no token, no password
// and no configurable allow list, so the profile itself is the credential and
// there is nothing else that could be misconfigured into opening the door.
const adminVPNNetwork = "10.80.253.0/24"

var adminNetwork *net.IPNet

func init() {
	_, network, err := net.ParseCIDR(adminVPNNetwork)
	if err != nil {
		panic("invalid admin network: " + err.Error())
	}
	adminNetwork = network
}

// peerIP is the address the request really came from. X-Forwarded-For is
// deliberately ignored: a client can set it, and this is an authorization
// decision.
func peerIP(r *http.Request) net.IP {
	host, _, err := net.SplitHostPort(r.RemoteAddr)
	if err != nil {
		host = r.RemoteAddr
	}
	return net.ParseIP(host)
}

// isAdminRequest has no exception at all, not even for debug builds or for the
// loopback of the game server itself: an organizer is somebody holding an admin
// WireGuard profile, and nothing else. To work on the control room locally,
// connect to the game with one of the profiles in router/configs/admins/.
func isAdminRequest(r *http.Request) bool {
	ip := peerIP(r)
	return ip != nil && adminNetwork.Contains(ip)
}

func adminOnly(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if !isAdminRequest(r) {
			http.Error(w, "The control room is only reachable from an admin VPN profile", http.StatusForbidden)
			return
		}
		next(w, r)
	}
}

// adminActor labels the audit log with the profile the action came from.
func adminActor(r *http.Request) string {
	if ip := peerIP(r); ip != nil {
		return "admin@" + ip.String()
	}
	return "admin"
}

// handleAdminWhoami is the only unauthenticated endpoint: the scoreboard calls
// it to decide whether to show the control room at all.
func handleAdminWhoami(w http.ResponseWriter, r *http.Request) {
	address := ""
	if ip := peerIP(r); ip != nil {
		address = ip.String()
	}
	writeJSON(w, map[string]interface{}{
		"admin": isAdminRequest(r),
		"ip":    address,
	})
}

// ----------------------------------------------------------------------------
// audit log
// ----------------------------------------------------------------------------

func auditLog(actor string, action string, target string, details string) {
	if conn == nil {
		return
	}
	go func() {
		if _, err := conn.NewInsert().Model(&db.AuditLog{
			At:      time.Now(),
			Actor:   actor,
			Action:  action,
			Target:  target,
			Details: details,
		}).Exec(context.Background()); err != nil {
			log.Debugf("Error writing audit log: %v", err)
		}
	}()
}

// ----------------------------------------------------------------------------
// overview
// ----------------------------------------------------------------------------

type adminOverview struct {
	Round        int             `json:"round"`
	Settings     Settings        `json:"settings"`
	NetworkState string          `json:"network_state"`
	Node         string          `json:"node"`
	Nodes        []NodeStatus    `json:"nodes"`
	Workers      []WorkerView    `json:"workers"`
	Queue        DispatcherStats `json:"queue"`
	Capacity     int             `json:"capacity"`
	Teams        int             `json:"teams"`
	Services     int             `json:"services"`
	NextRoundAt  string          `json:"next_round_at"`
	ServerTime   string          `json:"server_time"`
}

func handleAdminOverview(w http.ResponseWriter, r *http.Request) {
	round := db.GetExposedRound()
	writeJSON(w, adminOverview{
		Round:        round,
		Settings:     gs.Settings(),
		NetworkState: gs.NetworkState(),
		Node:         processNode,
		Nodes:        nodeRegistry.Statuses(),
		Workers:      registry.List(),
		Queue:        dispatcher.Stats(),
		Capacity:     registry.Capacity(),
		Teams:        len(gs.Teams()),
		Services:     len(gs.Services()),
		NextRoundAt:  calcRoundStartTime(uint(round + 2)).Format(time.RFC3339),
		ServerTime:   time.Now().Format(time.RFC3339),
	})
}

// ----------------------------------------------------------------------------
// settings
// ----------------------------------------------------------------------------

type settingsPatch struct {
	TickTime            *int64   `json:"tick_time"`
	FlagExpireTicks     *int64   `json:"flag_expire_ticks"`
	InitialServiceScore *float64 `json:"initial_service_score"`
	MaxFlagsPerRequest  *int     `json:"max_flags_per_request"`
	SubmissionTimeout   *float64 `json:"submission_timeout"`
	GraceTime           *int64   `json:"grace_time"`
	CheckerTimeout      *int64   `json:"checker_timeout"`
	EndTime             *string  `json:"end_time"`
	ScoreboardFreezeAt  *string  `json:"scoreboard_freeze_time"`
	ClearSubmissionTmo  bool     `json:"clear_submission_timeout"`
	ClearEndTime        bool     `json:"clear_end_time"`
	ClearFreezeTime     bool     `json:"clear_scoreboard_freeze_time"`
}

func handleAdminGetSettings(w http.ResponseWriter, r *http.Request) {
	writeJSON(w, gs.Settings())
}

func handleAdminPatchSettings(w http.ResponseWriter, r *http.Request) {
	var patch settingsPatch
	if err := json.NewDecoder(r.Body).Decode(&patch); err != nil {
		http.Error(w, "Invalid request", http.StatusBadRequest)
		return
	}

	configPatch := map[string]interface{}{}
	changed := make([]string, 0)

	if patch.TickTime != nil && *patch.TickTime > 0 {
		writeSetting(setTickTime, strconv.FormatInt(*patch.TickTime, 10))
		configPatch["tick_time"] = *patch.TickTime
		changed = append(changed, "tick_time")
	}
	if patch.FlagExpireTicks != nil && *patch.FlagExpireTicks > 0 {
		writeSetting(setFlagExpireTicks, strconv.FormatInt(*patch.FlagExpireTicks, 10))
		configPatch["flag_expire_ticks"] = *patch.FlagExpireTicks
		changed = append(changed, "flag_expire_ticks")
	}
	if patch.InitialServiceScore != nil && *patch.InitialServiceScore > 0 {
		writeSetting(setInitialScore, strconv.FormatFloat(*patch.InitialServiceScore, 'f', -1, 64))
		configPatch["initial_service_score"] = *patch.InitialServiceScore
		changed = append(changed, "initial_service_score")
	}
	if patch.MaxFlagsPerRequest != nil && *patch.MaxFlagsPerRequest > 0 {
		writeSetting(setMaxFlags, strconv.Itoa(*patch.MaxFlagsPerRequest))
		configPatch["max_flags_per_request"] = *patch.MaxFlagsPerRequest
		changed = append(changed, "max_flags_per_request")
	}
	if patch.ClearSubmissionTmo {
		writeSetting(setSubmissionTmo, "")
		configPatch["submission_timeout"] = nil
		changed = append(changed, "submission_timeout")
	} else if patch.SubmissionTimeout != nil {
		writeSetting(setSubmissionTmo, strconv.FormatFloat(*patch.SubmissionTimeout, 'f', -1, 64))
		configPatch["submission_timeout"] = *patch.SubmissionTimeout
		changed = append(changed, "submission_timeout")
	}
	if patch.GraceTime != nil && *patch.GraceTime >= 0 {
		writeSetting(setGraceTime, strconv.FormatInt(*patch.GraceTime, 10))
		configPatch["grace_time"] = *patch.GraceTime
		changed = append(changed, "grace_time")
	}
	if patch.CheckerTimeout != nil && *patch.CheckerTimeout > 0 {
		writeSetting(setCheckerTimeout, strconv.FormatInt(*patch.CheckerTimeout, 10))
		configPatch["checker_timeout"] = *patch.CheckerTimeout
		changed = append(changed, "checker_timeout")
	}
	if patch.ClearEndTime {
		writeSetting(setEndTime, "")
		configPatch["end_time"] = nil
		changed = append(changed, "end_time")
	} else if patch.EndTime != nil {
		parsed, err := time.Parse(time.RFC3339, *patch.EndTime)
		if err != nil {
			http.Error(w, "Invalid end_time, expected RFC3339", http.StatusBadRequest)
			return
		}
		writeSetting(setEndTime, parsed.Format(time.RFC3339))
		configPatch["end_time"] = parsed.Format(time.RFC3339)
		changed = append(changed, "end_time")
	}
	if patch.ClearFreezeTime {
		gs.SetScoreboardFreezeAt(nil)
		changed = append(changed, "scoreboard_freeze_time")
	} else if patch.ScoreboardFreezeAt != nil {
		parsed, err := time.Parse(time.RFC3339, *patch.ScoreboardFreezeAt)
		if err != nil {
			http.Error(w, "Invalid scoreboard_freeze_time, expected RFC3339", http.StatusBadRequest)
			return
		}
		gs.SetScoreboardFreezeAt(&parsed)
		changed = append(changed, "scoreboard_freeze_time")
	}

	if len(configPatch) > 0 {
		if err := patchConfigFile(configPatch); err != nil {
			log.Errorf("Error writing config.json: %v", err)
		}
	}
	ReloadState()
	invalidateAllCaches()
	auditLog(adminActor(r), "settings.update", "", strings.Join(changed, ","))
	writeJSON(w, gs.Settings())
}

// ----------------------------------------------------------------------------
// teams
// ----------------------------------------------------------------------------

func handleAdminTeams(w http.ResponseWriter, r *http.Request) {
	type teamAdminView struct {
		TeamState
		Token string `json:"token"`
	}
	teams := gs.Teams()
	out := make([]teamAdminView, 0, len(teams))
	for _, team := range teams {
		out = append(out, teamAdminView{TeamState: team, Token: team.Token})
	}
	writeJSON(w, out)
}

type teamPatch struct {
	Name          *string `json:"name"`
	Image         *string `json:"image"`
	Nop           *bool   `json:"nop"`
	GameBanned    *bool   `json:"game_banned"`
	NetworkBanned *bool   `json:"network_banned"`
	BanReason     *string `json:"ban_reason"`
	RotateToken   bool    `json:"rotate_token"`
}

func handleAdminPatchTeam(w http.ResponseWriter, r *http.Request) {
	teamID, err := strconv.Atoi(mux.Vars(r)["team_id"])
	if err != nil {
		http.Error(w, "Invalid team id", http.StatusBadRequest)
		return
	}
	current := gs.TeamByID(teamID)
	if current == nil {
		http.Error(w, "Unknown team", http.StatusNotFound)
		return
	}
	var patch teamPatch
	if err := json.NewDecoder(r.Body).Decode(&patch); err != nil {
		http.Error(w, "Invalid request", http.StatusBadRequest)
		return
	}

	ctx := r.Context()
	query := conn.NewUpdate().Model((*db.Team)(nil)).Where("id = ?", teamID).Set("updated_at = ?", time.Now())
	changes := make([]string, 0)

	if patch.Name != nil && strings.TrimSpace(*patch.Name) != "" {
		query = query.Set("name = ?", strings.TrimSpace(*patch.Name))
		changes = append(changes, "name")
	}
	if patch.Image != nil {
		query = query.Set("image = ?", *patch.Image)
		changes = append(changes, "image")
	}
	if patch.Nop != nil {
		query = query.Set("nop = ?", *patch.Nop)
		changes = append(changes, "nop")
	}
	if patch.GameBanned != nil {
		query = query.Set("game_banned = ?", *patch.GameBanned)
		changes = append(changes, "game_banned")
	}
	if patch.BanReason != nil {
		query = query.Set("ban_reason = ?", *patch.BanReason)
		changes = append(changes, "ban_reason")
	}
	newToken := ""
	if patch.RotateToken {
		newToken = genToken()
		query = query.Set("token = ?", newToken)
		changes = append(changes, "token")
	}
	if patch.NetworkBanned != nil {
		query = query.Set("network_banned = ?", *patch.NetworkBanned)
		changes = append(changes, "network_banned")
	}

	if len(changes) == 0 {
		writeJSON(w, current)
		return
	}
	if _, err := query.Exec(ctx); err != nil {
		log.Errorf("Error updating team %v: %v", teamID, err)
		http.Error(w, "Internal server error", http.StatusInternalServerError)
		return
	}

	if patch.NetworkBanned != nil {
		var routeErr error
		if *patch.NetworkBanned {
			routeErr = CtfRouteBanTeam(teamID)
		} else {
			routeErr = CtfRouteUnbanTeam(teamID)
		}
		if routeErr != nil {
			log.Errorf("Error applying network ban on team %v: %v", teamID, routeErr)
		}
	}

	ReloadState()
	invalidateAllCaches()
	syncTeamsToConfigFile()
	auditLog(adminActor(r), "team.update", strconv.Itoa(teamID), strings.Join(changes, ","))
	writeJSON(w, gs.TeamByID(teamID))
}

// syncTeamsToConfigFile mirrors the runtime team list back into config.json so
// that run.py keeps generating the same infrastructure on the next restart.
func syncTeamsToConfigFile() {
	teams := gs.Teams()
	out := make([]map[string]interface{}, 0, len(teams))
	for _, team := range teams {
		out = append(out, map[string]interface{}{
			"id":    team.ID,
			"name":  team.Name,
			"token": team.Token,
			"nop":   team.Nop,
			"image": team.Image,
		})
	}
	if err := patchConfigFile(map[string]interface{}{"teams": out}); err != nil {
		log.Errorf("Error writing teams to config.json: %v", err)
	}
}

func genToken() string {
	const alphabet = "0123456789abcdef"
	randLock.Lock()
	defer randLock.Unlock()
	out := make([]byte, 64)
	for i := range out {
		out[i] = alphabet[randSrc.Intn(len(alphabet))]
	}
	return string(out)
}

// ----------------------------------------------------------------------------
// services
// ----------------------------------------------------------------------------

func handleAdminServices(w http.ResponseWriter, r *http.Request) {
	writeJSON(w, gs.Services())
}

func handleAdminPatchService(w http.ResponseWriter, r *http.Request) {
	name := mux.Vars(r)["service"]
	var patch struct {
		Enabled     *bool    `json:"enabled"`
		Weight      *float64 `json:"weight"`
		Description *string  `json:"description"`
	}
	if err := json.NewDecoder(r.Body).Decode(&patch); err != nil {
		http.Error(w, "Invalid request", http.StatusBadRequest)
		return
	}
	query := conn.NewUpdate().Model((*db.Service)(nil)).Where("name = ?", name).Set("updated_at = ?", time.Now())
	changes := make([]string, 0)
	if patch.Enabled != nil {
		query = query.Set("enabled = ?", *patch.Enabled)
		changes = append(changes, "enabled")
	}
	if patch.Weight != nil && *patch.Weight > 0 {
		query = query.Set("weight = ?", *patch.Weight)
		changes = append(changes, "weight")
	}
	if patch.Description != nil {
		query = query.Set("description = ?", *patch.Description)
		changes = append(changes, "description")
	}
	if len(changes) == 0 {
		writeJSON(w, gs.Services())
		return
	}
	if _, err := query.Exec(r.Context()); err != nil {
		http.Error(w, "Internal server error", http.StatusInternalServerError)
		return
	}
	ReloadState()
	invalidateAllCaches()
	auditLog(adminActor(r), "service.update", name, strings.Join(changes, ","))
	writeJSON(w, gs.Services())
}

// ----------------------------------------------------------------------------
// game control
// ----------------------------------------------------------------------------

func handleAdminNetwork(w http.ResponseWriter, r *http.Request) {
	action := mux.Vars(r)["action"]
	var err error
	switch action {
	case "freeze":
		err = CtfRouteFreeze()
	case "lock":
		err = CtfRouteLock()
	case "unlock":
		err = CtfRouteUnlock()
	default:
		http.Error(w, "Unknown action", http.StatusBadRequest)
		return
	}
	auditLog(adminActor(r), "network."+action, "", errText(err))
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	writeJSON(w, map[string]string{"network_state": gs.NetworkState()})
}

func errText(err error) string {
	if err == nil {
		return "ok"
	}
	return err.Error()
}

func handleAdminFreeze(w http.ResponseWriter, r *http.Request) {
	var req struct {
		Frozen bool    `json:"frozen"`
		Round  *int    `json:"round"`
		At     *string `json:"at"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, "Invalid request", http.StatusBadRequest)
		return
	}
	if req.At != nil {
		parsed, err := time.Parse(time.RFC3339, *req.At)
		if err != nil {
			http.Error(w, "Invalid at, expected RFC3339", http.StatusBadRequest)
			return
		}
		gs.SetScoreboardFreezeAt(&parsed)
		auditLog(adminActor(r), "scoreboard.schedule_freeze", "", parsed.Format(time.RFC3339))
		writeJSON(w, gs.Settings())
		return
	}
	round := db.GetExposedRound()
	if req.Round != nil {
		round = *req.Round
	}
	gs.SetScoreboardFreeze(req.Frozen, round)
	if req.Frozen {
		auditLog(adminActor(r), "scoreboard.freeze", "", "round "+strconv.Itoa(round))
	} else {
		auditLog(adminActor(r), "scoreboard.unfreeze", "", "")
	}
	writeJSON(w, gs.Settings())
}

func handleAdminPause(w http.ResponseWriter, r *http.Request) {
	var req struct {
		Paused bool `json:"paused"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, "Invalid request", http.StatusBadRequest)
		return
	}
	gs.SetGamePaused(req.Paused)
	auditLog(adminActor(r), "game.pause", "", strconv.FormatBool(req.Paused))
	writeJSON(w, gs.Settings())
}

func handleAdminReload(w http.ResponseWriter, r *http.Request) {
	syncServicesFromDisk()
	ReloadState()
	initScoreboard()
	invalidateAllCaches()
	applyNetworkBans()
	auditLog(adminActor(r), "state.reload", "", "")
	writeJSON(w, map[string]interface{}{"teams": len(gs.Teams()), "services": len(gs.Services())})
}

// ----------------------------------------------------------------------------
// cluster
// ----------------------------------------------------------------------------

func handleAdminWorkers(w http.ResponseWriter, r *http.Request) {
	writeJSON(w, map[string]interface{}{
		"workers":  registry.List(),
		"queue":    dispatcher.Stats(),
		"capacity": registry.Capacity(),
	})
}

func handleAdminDropWorker(w http.ResponseWriter, r *http.Request) {
	id := mux.Vars(r)["worker_id"]
	registry.Remove(id)
	auditLog(adminActor(r), "worker.drop", id, "")
	w.WriteHeader(http.StatusOK)
}

func handleAdminJobs(w http.ResponseWriter, r *http.Request) {
	rows := make([]db.CheckJob, 0)
	query := conn.NewSelect().Model(&rows).Order("id DESC").Limit(500)
	if round := r.URL.Query().Get("round"); round != "" {
		query = query.Where("round = ?", round)
	}
	if service := r.URL.Query().Get("service"); service != "" {
		query = query.Where("service = ?", service)
	}
	if state := r.URL.Query().Get("state"); state != "" {
		query = query.Where("state = ?", state)
	}
	if err := query.Scan(r.Context()); err != nil {
		http.Error(w, "Internal server error", http.StatusInternalServerError)
		return
	}
	writeJSON(w, rows)
}

// ----------------------------------------------------------------------------
// forensics
// ----------------------------------------------------------------------------

type attackEdge struct {
	FromTeam int     `json:"from_team"`
	ToTeam   int     `json:"to_team"`
	Service  string  `json:"service"`
	Flags    int     `json:"flags"`
	Points   float64 `json:"points"`
}

// handleAdminAttackGraph shows who is stealing from whom: the cheapest and most
// reliable "who is attacking" signal available, straight from the submissions.
func handleAdminAttackGraph(w http.ResponseWriter, r *http.Request) {
	type row struct {
		Attacker string  `bun:"attacker"`
		Victim   string  `bun:"victim"`
		Service  string  `bun:"service"`
		Flags    int     `bun:"flags"`
		Points   float64 `bun:"points"`
	}
	rows := make([]row, 0)
	query := conn.NewSelect().Model((*db.FlagSubmission)(nil)).
		ColumnExpr("submit.team AS attacker").
		ColumnExpr("flag.team AS victim").
		ColumnExpr("flag.service AS service").
		ColumnExpr("count(*) AS flags").
		ColumnExpr("coalesce(sum(submit.offensive_points), 0) AS points").
		Join("JOIN flags flag ON flag.id = submit.flag_id").
		GroupExpr("submit.team, flag.team, flag.service")

	if since := r.URL.Query().Get("since_round"); since != "" {
		query = query.Where("submit.round >= ?", since)
	}
	if err := query.Scan(r.Context(), &rows); err != nil {
		log.Errorf("Error building attack graph: %v", err)
		http.Error(w, "Internal server error", http.StatusInternalServerError)
		return
	}
	edges := make([]attackEdge, 0, len(rows))
	for _, entry := range rows {
		edges = append(edges, attackEdge{
			FromTeam: extractTeamID(entry.Attacker),
			ToTeam:   extractTeamID(entry.Victim),
			Service:  entry.Service,
			Flags:    entry.Flags,
			Points:   entry.Points,
		})
	}
	writeJSON(w, edges)
}

func handleAdminAudit(w http.ResponseWriter, r *http.Request) {
	rows := make([]db.AuditLog, 0)
	if err := conn.NewSelect().Model(&rows).Order("id DESC").Limit(300).Scan(r.Context()); err != nil {
		http.Error(w, "Internal server error", http.StatusInternalServerError)
		return
	}
	writeJSON(w, rows)
}

func handleAdminFlags(w http.ResponseWriter, r *http.Request) {
	rows := make([]db.Flag, 0)
	query := conn.NewSelect().Model(&rows).Order("round DESC").Limit(300)
	if team := r.URL.Query().Get("team"); team != "" {
		if id, err := strconv.Atoi(team); err == nil {
			query = query.Where("team = ?", teamIDToIP(id))
		}
	}
	if service := r.URL.Query().Get("service"); service != "" {
		query = query.Where("service = ?", service)
	}
	if round := r.URL.Query().Get("round"); round != "" {
		query = query.Where("round = ?", round)
	}
	if err := query.Scan(r.Context()); err != nil {
		http.Error(w, "Internal server error", http.StatusInternalServerError)
		return
	}
	writeJSON(w, rows)
}

// ----------------------------------------------------------------------------
// announcements and manual scoring
// ----------------------------------------------------------------------------

func handleAdminCreateAnnouncement(w http.ResponseWriter, r *http.Request) {
	var req struct {
		Title    string `json:"title"`
		Body     string `json:"body"`
		Severity string `json:"severity"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil || strings.TrimSpace(req.Title) == "" {
		http.Error(w, "Invalid request", http.StatusBadRequest)
		return
	}
	if req.Severity == "" {
		req.Severity = "info"
	}
	row := &db.Announcement{
		At:       time.Now(),
		Title:    req.Title,
		Body:     req.Body,
		Severity: req.Severity,
		Visible:  true,
		Author:   "admin",
	}
	if _, err := conn.NewInsert().Model(row).Exec(r.Context()); err != nil {
		http.Error(w, "Internal server error", http.StatusInternalServerError)
		return
	}
	auditLog(adminActor(r), "announcement.create", req.Title, req.Severity)
	writeJSON(w, row)
}

func handleAdminDeleteAnnouncement(w http.ResponseWriter, r *http.Request) {
	id := mux.Vars(r)["id"]
	if _, err := conn.NewUpdate().Model((*db.Announcement)(nil)).Set("visible = FALSE").Where("id = ?", id).Exec(r.Context()); err != nil {
		http.Error(w, "Internal server error", http.StatusInternalServerError)
		return
	}
	auditLog(adminActor(r), "announcement.delete", id, "")
	w.WriteHeader(http.StatusOK)
}

// ----------------------------------------------------------------------------
// routing
// ----------------------------------------------------------------------------

func registerAdminRoutes(router *mux.Router) {
	admin := router.PathPrefix("/api/admin").Subrouter()
	get := func(path string, handler http.HandlerFunc) {
		admin.HandleFunc(path, adminOnly(handler)).Methods("GET")
	}
	post := func(path string, handler http.HandlerFunc) {
		admin.HandleFunc(path, adminOnly(handler)).Methods("POST")
	}
	patch := func(path string, handler http.HandlerFunc) {
		admin.HandleFunc(path, adminOnly(handler)).Methods("PATCH")
	}

	router.HandleFunc("/api/admin/whoami", handleAdminWhoami).Methods("GET")

	get("/overview", handleAdminOverview)
	get("/settings", handleAdminGetSettings)
	patch("/settings", handleAdminPatchSettings)
	get("/teams", handleAdminTeams)
	patch("/teams/{team_id}", handleAdminPatchTeam)
	post("/teams/{team_id}/reset-vm", handleAdminResetVM)
	get("/services", handleAdminServices)
	patch("/services/{service}", handleAdminPatchService)
	post("/network/{action}", handleAdminNetwork)
	post("/scoreboard/freeze", handleAdminFreeze)
	post("/game/pause", handleAdminPause)
	post("/reload", handleAdminReload)
	get("/workers", handleAdminWorkers)
	admin.HandleFunc("/workers/{worker_id}", adminOnly(handleAdminDropWorker)).Methods("DELETE")
	get("/jobs", handleAdminJobs)
	get("/attack-graph", handleAdminAttackGraph)
	get("/submissions", handleAdminSubmissions)
	get("/submissions/stats", handleAdminSubmissionStats)
	get("/audit", handleAdminAudit)
	get("/flags", handleAdminFlags)
	get("/traffic", handleAdminTraffic)
	get("/traffic/matrix", handleAdminTrafficMatrix)
	get("/traffic/peers", handleAdminPeerTraffic)
	get("/vpn/profiles", handleAdminVPNProfiles)
	post("/vpn/profiles/{address}/suspend", handleAdminSuspendProfile)
	get("/pcap/status", handleAdminPcapStatus)
	get("/pcap/download", handleAdminPcapDownload)
	post("/announcements", handleAdminCreateAnnouncement)
	admin.HandleFunc("/announcements/{id}", adminOnly(handleAdminDeleteAnnouncement)).Methods("DELETE")
}
