[Interface]
PrivateKey = OJ+c+ipMbRA50rQDFK3UFoUpeCzLBm8cP+8WBF8f1Vc=
Address = 10.80.253.20/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = 1F/fw9ljRCJEJBhBjo/W7bLQgSH1iUN8hkS2ue9k9fM=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
