[Interface]
PrivateKey = QORrVhfTHyDxgdrZuHa53UfpkJWd3XHhq7VuOsA7kXA=
Address = 10.80.253.7/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = 1mMZPII+IaRfJx9lPi1L74SdoJxB1q5w6bixpyk9imI=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
