[Interface]
PrivateKey = CPzv1D562p2uXBBDC1+uC2sg+n39V0gkLL9r9VesKW0=
Address = 10.80.253.29/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = eDaiI+GdmhkC+fp1LH9LH/WPpabLcoacHeuFBs29oDk=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
