[Interface]
PrivateKey = kKr3pbem8ZmU0b2c1FISq6LlKHXyjee6jd/oROE+HFI=
Address = 10.80.253.3/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = wOsfTG6hC/nvjJeq3+yJGiFMfTwf92Gz2ew97jfJ5Uw=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
