[Interface]
PrivateKey = IGx2cIB6BZpIvDVtsAlkpoA0VMMKDxWFz8bn0tz3Ul8=
Address = 10.80.253.8/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = 3LtAEMx3llBTP68C0Sne5UYp+U+8MUSyLe6evmwfqv0=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
