[Interface]
PrivateKey = IKR0cjY1Qwo5kFdc4EWP6bWi1FCWGQVqTTQMsftMimg=
Address = 10.80.253.13/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = s1wSH2vgPOu/pHvmSlR6kM+XBWOAMJjTXqeTYgbKGFk=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
