[Interface]
PrivateKey = 2NVp9vixwUDWS0kaD8yM3t2oOK95s1lLWP+dIFssCWs=
Address = 10.80.253.25/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = P7aQHzfsCSeQM/MnUS3ju31qjymKtTrv0z4HOeNepxY=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
