[Interface]
PrivateKey = mJeqJnVMPeUI+acuAxp9hxOD19MXotqraaDk/teP22M=
Address = 10.80.253.28/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = gcHNoPpIQKKe8vJ/+tCnGMYHAjlkKGC/RRBnRe1jcWE=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
