[Interface]
PrivateKey = MNCxvO0LAdB64CmaU16RRG4/pP6jnEv4sUMiG9EeoVE=
Address = 10.80.253.24/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = pczvNRDW5H2A0fq7gY7J/T7L00+V+5q7SDR4u6WKfSs=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
