[Interface]
PrivateKey = 6J1cFkXgRcnKo061lzwC6ftei6eaIbXvlkUWTdwK+kA=
Address = 10.80.253.18/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = 8E5gSQbNrQKfip0+zX2agM06wla8rbkaAbpmM2ZZUG4=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = 104.167.30.180:51000
PersistentKeepalive = 5
