[Interface]
PrivateKey = ELri9KRg5FTQx73u58KYvpfHS3Hup4jTGvHtupy17Ew=
Address = 10.60.1.1/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = MctB0QjEC2g5fZKMOIgw0O9SHNjmKQxdvpwfoC+9pns=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = router:51820
PersistentKeepalive = 5
