[Interface]
PrivateKey = GJU/T9urX/ELj2Xl2Vo0aLI2Si+WUMPPQXE45zW8gXY=
Address = 10.60.3.1/32
MTU = 1280

[Peer]
PublicKey = Z4PNn/HcerRDW5bm4PzgapT/o0LFvz5V1X/5bvOLvzU=
PresharedKey = Sn1LtFhkOUdAhNT6y9QcCJJR4JyfRgioYJfn9vHyqPg=
AllowedIPs = 10.10.0.0/24, 10.60.0.0/16, 10.80.0.0/16
Endpoint = router:51820
PersistentKeepalive = 5
